[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topic = "customers/data_request"
path = "/api/webhooks/customers-data-request"

[[webhooks.subscriptions]]
topic = "customers/redact"
path = "/api/webhooks/customers-redact"

[[webhooks.subscriptions]]
topic = "shop/redact"
path = "/api/webhooks/shop-redact"
